configure: silence -Wignored-attributes
clang does not support this attribute. and it complains:

core/memory.cc:1228:18: error: attribute 'cold' ignored, because it
cannot be applied to a type [-Werror,-Wignored-attributes]
        [&] () [[gnu::cold]] {
                 ^

Signed-off-by: Kefu Chai <tchaikov@gmail.com>