tests/unit/steam_reader: use size_t for _remaining_size
because not all platform use the same type for size_t and uint64_t, to be
on the safe side, and more error-prone, we'd better use the same type.

this change helps to address the following FTBFS:

tests/unit/stream_reader_test.cc:58:28: error: no matching function for call to 'min'
        _remaining_size -= std::min(_remaining_size, n);
                           ^~~~~~~~

Signed-off-by: Kefu Chai <tchaikov@gmail.com>