util/log, rpc, core: use compile-time formatting with fmtlib >= 8.0
fmtlib v8.0.0 comes with compile-time formatting and more importantly,
compile-time format string checking.
see https://github.com/fmtlib/fmt/releases/tag/8.0.0 .

in this change:

* util/log: use fmt::format_string<> for passing format string
* util/log: disable failed_to_log() handling, as the compile-time
  check is able to take care of the formatting failure at compile-time.
* tests/unit: disable format_error_test when compiling with fmtlib >=
  8.0
* util/log: add overloads for printing a single runtime string
* util/log: change `log(log_level level, format_info fmt, Args&&... args)`
  to `log(log_level level, Fmt fmt, Args&&... args)`, so it won't be
  matched by the compiler when it tries to look up a function like

  ```c++
  seastar_logger.log(lvl,
  "IO queue uses {:.2f}ms latency goal for device {}",
  goal.count() * 1000, cfg.devid);
  ```
  without the change, both `void log(log_level level,
  fmt::format_string<Args...> fmt, Args&&... args)` and the old
  ```void log(log_level level, format_info fmt, Args&&... args)`
  would be candidates of this call, and hence they are ambigous.
  with this change, if Seastar is compiled with fmt v8 and up,
  only the new API would be matched.

when compiling with fmtlib v9.0.0, we'd have following compiling
failure if the format string is malformed, like

 logger.trace("{}: failed ({})", e.what());

and the error message would look like:

../src/seastar-application.cc:181:15:   in ‘constexpr’ expansion of ‘fmt::v9::basic_format_string<char, const seastar::basic_sstring<char, unsigned int, 15, true>&>("{}: reap_sqes({})")’
../third-party/fmt/include/fmt/core.h:3116:40:   in ‘constexpr’ expansion of ‘fmt::v9::detail::parse_format_string<true, char, fmt::v9::detail::format_string_checker<char, fmt::v9::detail::error_handler, seastar::$
../third-party/fmt/include/fmt/core.h:2658:44:   in ‘constexpr’ expansion of ‘fmt::v9::detail::parse_replacement_field<char, fmt::v9::detail::format_string_checker<char, fmt::v9::detail::error_handler, seastar::ba$
../third-party/fmt/include/fmt/core.h:2623:51:   in ‘constexpr’ expansion of ‘(& handler)->fmt::v9::detail::format_string_checker<char, fmt::v9::detail::error_handler, seastar::basic_sstring<char, unsigned int, 15$
../third-party/fmt/include/fmt/core.h:2928:70:   in ‘constexpr’ expansion of ‘((fmt::v9::detail::format_string_checker<char, fmt::v9::detail::error_handler, seastar::basic_sstring<char, unsigned int, 15, true> >*)$
../third-party/fmt/include/fmt/core.h:742:40: error: ‘constexpr void fmt::v9::basic_format_parse_context<Char, ErrorHandler>::on_error(const char*) [with Char = char; ErrorHandler = fmt::v9::detail::error_handler]$
  742 |     if (id >= num_args_) this->on_error("argument not found");
      |                          ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
../third-party/fmt/include/fmt/core.h:713:22: note: ‘constexpr void fmt::v9::basic_format_parse_context<Char, ErrorHandler>::on_error(const char*) [with Char = char; ErrorHandler = fmt::v9::detail::error_handler]’$
  713 |   FMT_CONSTEXPR void on_error(const char* message) {
      |                      ^~~~~~~~
../third-party/fmt/include/fmt/core.h:714:27: error: call to non-‘constexpr’ function ‘void fmt::v9::detail::error_handler::on_error(const char*)’
  714 |     ErrorHandler::on_error(message);
      |     ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
../third-party/fmt/include/fmt/core.h:633:21: note: ‘void fmt::v9::detail::error_handler::on_error(const char*)’ declared here
  633 |   FMT_NORETURN void on_error(const char* message) {
      |                     ^~~~~~~~

when compiling with fmtlib v8.0.0, we have similar error messages.

please note, the formatter or the log writer could throw when the
formatted string is huge and results in out of memory. in that case,
we still want to print out minimum information of the logging message,
for instance, the source_location where the log is printed. in
existing implementation, this information is stored along with the
format string in `format_info`. but in the new implementataion we
don't have `format_info` anymore, as it would have to be a compile-time
constant. as an alternative, the backtrace is printed.

Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>