core/loop: drop unused parameters
this change helps to silence following warning from GCC-12:

seastar/include/seastar/core/loop.hh:500:57: error: unused parameter ‘begin’ [-Werror=unused-parameter]
  500 | iterator_range_estimate_vector_capacity(Iterator const& begin, Sentinel const& end, IteratorCategory category) {
      |                                         ~~~~~~~~~~~~~~~~^~~~~

Signed-off-by: Kefu Chai <tchaikov@gmail.com>