resource: move includes to the top of the source file
so we don't have `export`` files in the module purview. this addresses
the FTBFS with C++20, like
```
FAILED: src/CMakeFiles/seastar-module.dir/core/resource.cc.o
/usr/bin/clang++-18 -DBOOST_NO_CXX98_FUNCTION_BASE -DFMT_SHARED -DSEASTAR_API_LEVEL=7 -DSEASTAR_COROUTINES_ENABLED -DSEASTAR_MODULE -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_SSTRING -Dseastar_module_EXPORTS -I/home/circleci/project/include -I/home/circleci/project/build/debug/gen/include -I/home/circleci/project/src -g -std=c++20 -fPIC -U_FORTIFY_SOURCE -Wno-include-angled-in-module-purview -MD -MT src/CMakeFiles/seastar-module.dir/core/resource.cc.o -MF src/CMakeFiles/seastar-module.dir/core/resource.cc.o.d @src/CMakeFiles/seastar-module.dir/core/resource.cc.o.modmap -o src/CMakeFiles/seastar-module.dir/core/resource.cc.o -c /home/circleci/project/src/core/resource.cc
In file included from /home/circleci/project/src/core/resource.cc:707:
In file included from /home/circleci/project/include/seastar/core/resource.hh:24:
/home/circleci/project/include/seastar/util/std-compat.hh:79:1: error: export declaration can only be used within a module purview
   79 | SEASTAR_MODULE_EXPORT_BEGIN
      | ^
/home/circleci/project/include/seastar/util/modules.hh:26:39: note: expanded from macro 'SEASTAR_MODULE_EXPORT_BEGIN'
   26 | #  define SEASTAR_MODULE_EXPORT_BEGIN export {
      |                                       ^
/home/circleci/project/src/core/resource.cc:37:1: note: add 'export' here if this is intended to be a module interface unit
   37 | module seastar;
      | ^
      | export
```

Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>