Catch use-after-free bugs in usage of shared ptrs using Clang's consumed attributes
Clang provides consumed annotations, which are very useful for
statically catching use-after-free bugs in specific classes.

That's done by:
1) Marking class as consumable with: clang::consumable().
2) Annotates contructors with clang::return_typestate(), to inform
new objects are in "unconsumed" state.
3) Set state of objects moved as "consumed" using clang::set_typestate()
4) Methods that access the object will be annotated with
clang::callable_when(unconsumed).

This way, clang screams whenever a code path tries to access an
object that was moved, i.e. has consumed state.

For years, we have been suffering with user-after-free bug around
smart pointers.

Therefore, both shared_ptr and lw_shared_ptr will now benefit from
this static analysis (not enabled by default).

To enable it, one must use clang, of course, and also provide the
-Wconsumed flag. As the analysis can report false positives,
it's important to disable -Werror (possibly by overriding it with
-Wno-error), so to allow the compilation to run to its completion.

This tool was able to find 4 use-after-free bugs in Scylla so far.

```
Example of report by clang once it hits a possible use-after-free:
"sstables/mx/reader.cc:1705:58: error: invalid invocation of method 'operator*'
on object 'schema' while it is in the 'consumed' state [-Werror,-Wconsumed]
                legacy_reverse_slice_to_native_reverse_slice(*schema, slice.get()),
                        pc, std::move(trace_state), fwd, fwd_mr, monitor);"
```

Signed-off-by: Raphael S. Carvalho <raphaelsc@scylladb.com>