native-stack: do not use 0 as ip address if !_dhcp
since the branch is taken only if !_dhcp, there is no need to check
it again. also this annoys the clang-15 compiler which complains like:

seastar/src/net/native-stack.cc:200:51: error: incompatible operand types ('int' and 'const std::string')
        _inet.set_host_address(ipv4_address(_dhcp ? 0 : opts.host_ipv4_addr.get_value()));
                                                  ^ ~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Kefu Chai <tchaikov@gmail.com>